### ISSUE TITLE
Create an API endpoint to download data from NCBI - through Download tool of Candis.

### ISSUE THREAD

**Issue by rupav** [HelikarLab/candis#53]
This will be used to download data from [NCBI](https://www.ncbi.nlm.nih.gov/) into Candis.

**Checklist:** to implement 
- [x] Add API endpoint to call Entrez module.
- [x] Add GEO module
- [x] Implement Esearch 
- [x] Implement Esummary
- [x] Implement the logic as described in https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html#ExampleIII
- [x] Use socket.io for download progress.
- [ ] Add test cases
- [x] Remove time.sleep()
- [x] Setup logging instead of print statements. - refer #137 
- [x] Start redis server from ~Procfile~ (now using honho Manager class) - use different port if initialized. - refer #99 
- [ ] ftplib is used for downloading- show progress bar (It shows up with 'wget')
- [x] Integrate with front-end. - refer issue #110 **TODO**: Improvements needed as mentioned in the related PRs to #110 
- [ ] Add JS test cases for the same.
- [ ] Instead of using requests.Timeout error, use custom error class.
